# Generated by Django 6.1.1 on 2026-09-28 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_guest',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1, help_text='Total number of guests for this booking', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
