# Generated by Django 6.1.1 on 2026-09-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
