# Generated by Django 6.1.1 on 2026-09-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_order_room_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='subtotal',
        ),
    ]
